package spring.transaction;

import javax.sql.DataSource;

import org.springframework.context.ApplicationContext;
import org.springframework.context.support.ClassPathXmlApplicationContext;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.transaction.PlatformTransactionManager;

import spring.transaction.model.AddressModel;
import spring.transaction.model.UserModel;
import spring.transaction.service.IAddressService;
import spring.transaction.service.IUserService;

public class TransactionTest
{
    private static ApplicationContext ctx;
    private static PlatformTransactionManager txManager;
    private static DataSource dataSource;
    private static JdbcTemplate jdbcTemplate;

    // id自增主键从0开始
    // private static final String CREATE_TABLE_SQL = "create table test"
    // + "(id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " + "name
    // varchar(100))";
    // private static final String DROP_TABLE_SQL = "drop table test";

    private static final String CREATE_USER_TABLE_SQL = "create table user" + "(id int auto_increment PRIMARY KEY, "
            + "name text)";

    private static final String DROP_USER_TABLE_SQL = "drop table user";

    private static final String CREATE_ADDRESS_TABLE_SQL = "create table address "
            + "(id int  auto_increment PRIMARY KEY, " + "province text,city text, street text, user_id int)";

    private static final String DROP_ADDRESS_TABLE_SQL = "drop table address";

    private static final String INSERT_SQL = "insert into test(name) values(?)";
    private static final String COUNT_SQL = "select count(*) from test";

    private static UserModel createDefaultUserModel()
    {
        UserModel user = new UserModel();
        user.setName("test");
        AddressModel address = new AddressModel();
        address.setProvince("beijing");
        address.setCity("beijing");
        address.setStreet("haidian");
        user.setAddress(address);
        return user;
    }

    public static void testServiceTransaction()
    {
        String[] configLocations = new String[] { "spring/transaction/transaction.xml" };
        ClassPathXmlApplicationContext ctx = new ClassPathXmlApplicationContext(configLocations);

        DataSource dataSource = ctx.getBean(DataSource.class);
        JdbcTemplate jdbcTemplate = new JdbcTemplate(dataSource);
        // jdbcTemplate.update(CREATE_USER_TABLE_SQL);
        // jdbcTemplate.update(CREATE_ADDRESS_TABLE_SQL);

        IUserService userService = ctx.getBean("userService", IUserService.class);
        IAddressService addressService = ctx.getBean("addressService", IAddressService.class);
        UserModel user = createDefaultUserModel();
        try
        {
            userService.save(user);
        } catch (Exception e)
        {
            System.out.println(e.getMessage());
        }
        System.out.println(userService.countAll());
        System.out.println(addressService.countAll());

        // Assert.assertEquals(1, userService.countAll());
        // Assert.assertEquals(1, addressService.countAll());
        ctx.close();
        // jdbcTemplate2.update(DROP_USER_TABLE_SQL);
        // jdbcTemplate2.update(DROP_ADDRESS_TABLE_SQL);
    }

    public static void main(String[] args)
    {
        testServiceTransaction();
    }
}
